version: '2.2'
services:
    db:
        container_name: db_sbtur
        image: postgres:10.5
        ports:
            - "5432:5432"
        env_file:
            ./environment/db.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    sbtur:
        container_name: sbtur
        build: .
        command: >
            bash -c " while !</dev/tcp/db/5432; do sleep 1; done
            && python manage.py makemigrations
            && python manage.py migrate
            && python manage.py loaddata initial.json
            && python manage.py createsuperuser_api --noinput
            && python manage.py runserver 0.0.0.0:8000"
        ports:
            - '8000:8000'
        env_file:
            ./environment/sbtur.env
        volumes:
            - .:/sbturAPI
        depends_on:
            - db